/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#0D9488',
        'primary-dark': '#0F766E',
        'primary-light': '#CCFBF1',
        'background-light': '#F8FAFC',
        'background-dark': '#0F172A',
        'text-main': '#334155',
        'text-sub': '#64748B',
        // MD3 color tokens for new-design experiment
        md: {
          primary: '#00685f',
          'primary-container': '#008378',
          'on-primary': '#ffffff',
          'on-primary-container': '#f4fffc',
          secondary: '#3f6560',
          'secondary-container': '#c2ebe3',
          'on-secondary': '#ffffff',
          'on-secondary-container': '#456b66',
          tertiary: '#924628',
          'tertiary-container': '#b05e3d',
          'on-tertiary': '#ffffff',
          'on-tertiary-container': '#fffbff',
          error: '#ba1a1a',
          'error-container': '#ffdad6',
          'on-error': '#ffffff',
          'on-error-container': '#93000a',
          surface: '#f6fafe',
          'surface-dim': '#d6dade',
          'surface-bright': '#f6fafe',
          'surface-container-lowest': '#ffffff',
          'surface-container-low': '#f0f4f8',
          'surface-container': '#eaeef2',
          'surface-container-high': '#e4e9ed',
          'surface-container-highest': '#dfe3e7',
          'on-surface': '#171c1f',
          'on-surface-variant': '#3d4947',
          outline: '#6d7a77',
          'outline-variant': '#bcc9c6',
          'inverse-surface': '#2c3134',
          'inverse-on-surface': '#edf1f5',
          'inverse-primary': '#6bd8cb',
          'primary-fixed': '#89f5e7',
          'primary-fixed-dim': '#6bd8cb',
          'secondary-fixed': '#c2ebe3',
          'secondary-fixed-dim': '#a6cfc8',
        },
      },
      fontFamily: {
        display: ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        soft: '0 20px 40px -4px rgba(0, 0, 0, 0.08), 0 8px 16px -4px rgba(0, 0, 0, 0.04)',
      },
    },
  },
  plugins: [],
};
